CC_Adminstration/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home_Page, name='Home_Page'),
    path('accounts/', include('Accounts.urls')),
    path('general/', include('General.urls')),
    path('mech_dep/', include('Mechanisms_Department.urls')),
    path('fin_dep/', include('Financial_Department.urls')),
    path('sections/', include('Sections.urls')),
    #path('authen/', include('django.contrib.auth.urls')),
]

General/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('permissions/', views.Permissions_Page, name='Permissions_Page'),
    path('save_permissions/', views.Save_Permissions, name='Save_Permissions'),
]

Financial_Department/models.py
from enum import auto
from django.db import models


class Main_Balance(models.Model):
    Year     = models.CharField(primary_key=True, unique=True, max_length=4)
    Volume   = models.IntegerField(blank=True, default=0)
    Duration = models.CharField(max_length=16, blank=True, default='D')

    def __str__(self):
        return self.Year


class SubBalances(models.Model):
    SubBalance_ID = models.CharField(primary_key=True, unique=True, max_length=128)
    Account       = models.CharField(max_length=64, blank=True, default='D')
    Year          = models.ForeignKey(Main_Balance, on_delete=models.CASCADE)
    Volume        = models.IntegerField(blank=True, default=0)
    Duration      = models.CharField(max_length=16, blank=True, default='D')

    def __str__(self):
        return self.Account


class SubBalance_Items(models.Model):
    SubBalanceItem_ID  = models.CharField(primary_key=True, unique=True, max_length=128)
    Year               = models.ForeignKey(Main_Balance, on_delete=models.CASCADE)
    Account            = models.ForeignKey(SubBalances, on_delete=models.CASCADE)
    Item               = models.CharField(max_length=64, blank=True, default='D')
    Volume             = models.IntegerField(blank=True, default=0)
    Duration           = models.CharField(max_length=16, blank=True, default='D')

    def __str__(self):
        return f'{self.Account}_{self.Year} - {self.Item}'


class Exchange_Orders(models.Model):
    Order_ID         = models.CharField(primary_key=True, unique=True, max_length=128)
    Order_No         = models.CharField(max_length=4, blank=True, default='D')
    Order_Date       = models.DateField(auto_now=False, auto_now_add=False)
    Order_Value      = models.IntegerField(blank=True, default=0)
    Year             = models.ForeignKey(Main_Balance, on_delete=models.CASCADE)
    SubBalance       = models.ForeignKey(SubBalances, on_delete=models.CASCADE)
    SubBalanceItem   = models.ForeignKey(SubBalance_Items, on_delete=models.CASCADE)
    Creditor_Acc     = models.CharField(max_length=64, blank=True, default='D')
    Creditor_No      = models.CharField(max_length=64, blank=True, default='D')
    Debtor_Acc       = models.CharField(max_length=64, blank=True, default='D')
    Debtor_No        = models.CharField(max_length=64, blank=True, default='D')
    Check_No         = models.CharField(max_length=64, blank=True, default='D')
    Check_Date       = models.DateField(auto_now_add=False, auto_now=False)
    Recipient        = models.CharField(max_length=64, blank=True, default='D')

    def __str__(self):
        return self.Order_ID

Mechanisms_Department/models.py
from django.db import models

# Create your models here.
class Mechanism_Data(models.Model):
    MechanismID     = models.CharField(primary_key=True, max_length=6, unique=True)
    Ownership       = models.CharField(max_length=48, blank=True, default='D')
    Disposal        = models.CharField(max_length=120, blank=True, default='D')
    Brand           = models.CharField(max_length=320, blank=True, default='D')
    Model           = models.CharField(max_length=320, blank=True, default='D')
    Type            = models.CharField(max_length=320, blank=True, default='D')
    Fuel_Limit      = models.IntegerField(blank=True, default=0)
    Repair_Limit    = models.IntegerField(blank=True, default=0)

    def __str__(self):
        return str(self.MechanismID)


class Statements(models.Model):
    Statement_ID    = models.CharField(primary_key=True, unique=True, max_length=128)
    Requests_No     = models.CharField(max_length=320, blank=True, default='D')
    Statement_No    = models.CharField(max_length=3, blank=True, default='D')
    SubBalance      = models.CharField(max_length=32, blank=True, default='D')
    Statement_Value = models.IntegerField(blank=True, default=0)
    Statement_Type  = models.CharField(max_length=6, blank=True, default='D')
    Year            = models.CharField(max_length=4, blank=True, default='D')

    def __str__(self):
        return str(self.Statement_ID)


class Repair_Requests(models.Model):
    Request_ID     = models.CharField(primary_key=True, unique=True, max_length=16)
    Request_No     = models.CharField(max_length=10, blank=True, default='D')
    Request_Date   = models.DateField(auto_now=False, auto_now_add=False)
    Year           = models.CharField(max_length=16, blank=True, default='D')
    Month          = models.CharField(max_length=16, blank=True, default='D')
    Day            = models.CharField(max_length=16, blank=True, default='D')
    Mechanism_No   = models.ForeignKey(Mechanism_Data, on_delete=models.CASCADE, blank=True, default='D')
    KiloMeters     = models.IntegerField(blank=True, default=0)
    Ownership      = models.CharField(max_length=48, blank=True, default='D')
    Disposal       = models.CharField(max_length=120, blank=True, default='D')
    Model          = models.CharField(max_length=320, blank=True, default='D')
    Expected_Cost  = models.IntegerField(blank=True, default=0)
    Approval       = models.IntegerField(blank=True, default=0)
    Exchange_Date  = models.DateField(auto_now=False, auto_now_add=False, blank=True, null=True)
    Driver         = models.CharField(max_length=64, blank=True, default='D')
    Real_Cost      = models.IntegerField(blank=True, default=0)
    Repair_Type    = models.CharField(max_length=16, default='صيانة طارئة')
    Status         = models.CharField(max_length=32, blank=True, default='D')
    Statement      = models.CharField(max_length=64, blank=True, default='D')

    def __str__(self):
        return str(self.Request_ID)


class Mechanisms_Repairs(models.Model):
    Request_ID   = models.ForeignKey(Repair_Requests, on_delete=models.CASCADE, default='D')
    Mechanism_No = models.CharField(max_length=6, blank=True, default='D')
    Request_Date = models.DateField(auto_now=False, auto_now_add=False, blank=True, null=True)
    Year         = models.CharField(max_length=4, blank=True, default='D')
    Month        = models.CharField(max_length=2, blank=True, default='D')
    Day          = models.CharField(max_length=2, blank=True, default='D')
    KiloMeters   = models.CharField(max_length=6, blank=True, default='D')
    Part_Repair  = models.CharField(max_length=120, blank=True, default='D')
    Part_Count   = models.IntegerField(blank=True, default=0)
    Part_Type    = models.CharField(max_length=32, blank=True, default='D')
    Cost         = models.IntegerField(blank=True, default=0)
    Receipt_No   = models.CharField(max_length=6, blank=True, default='D')
    Store        = models.CharField(max_length=64, blank=True, default='D')


    def __str__(self):
        return self.Part_Repair


class Parts_and_Repaires(models.Model):
    Name = models.CharField(max_length=320, blank=True, default='D')
    Type = models.CharField(max_length=320, blank=True, default='D')

    def __str__(self):
        return self.Name


class Drivers(models.Model):
    Driver_Name  = models.CharField(max_length=64, blank=True, default='D')
    Office       = models.CharField(max_length=64, blank=True, default='D')
    Mechanism_No = models.ForeignKey(Mechanism_Data, on_delete=models.CASCADE, blank=True, default='D')
    Disposal     = models.CharField(max_length=64, blank=True, default='D')

    def __str__(self):
        return self.Driver_Name


class Stores(models.Model):
    Store_Name = models.CharField(max_length=64, blank=True, default='D')
    Address    = models.CharField(max_length=128, blank=True, default='D')
    Email      = models.CharField(max_length=64, blank=True, default='D')
    PhoneNo    = models.CharField(max_length=16, blank=True, default='D')
    Mobile     = models.CharField(max_length=16, blank=True, default='D')

    def __str__(self):
        return self.Store_Name


class Receipts(models.Model):
    Receipt_ID    = models.CharField(primary_key=True, unique=True, max_length=64)
    Receipt_No    = models.CharField(max_length=16, blank=True, default='D')
    Request_ID    = models.ForeignKey(Repair_Requests, on_delete=models.CASCADE, blank=True, default='D')
    Receipt_Value = models.IntegerField(blank=True, default=0)
    Store_Name    = models.CharField(max_length=32, blank=True, default='D')
    Receipt_Date  = models.DateField(auto_now=False, auto_now_add=False)

    def __str__(self):
        return f"{self.Receipt_ID}__{self.Store_Name}"

templates/Fin_Dep/add_credit.html
{% extends 'base.html' %}

{% block SideBar %}
  {% include 'Fin_Dep/section_tasks.html' %}
{% endblock SideBar %}

{% block MainContainer %}
{% if perms.financial_department.add_subbalances and perms.financial_department.add_balance_items %}

{% else %}
  <h1>عذرا,ليس لديك صلاحيات لعرض هذه الصفحة.</h1>
{% endif %}
{% endblock MainContainer %}

templates/Fin_Dep/requests_aggrement.html
{% extends 'base.html' %}

{% block SideBar %}
  {% include 'Fin_Dep/section_tasks.html' %}
{% endblock SideBar %}

{% block MainContainer %}
{% if perms.mechanisms_department.view_repair_request and perms.mechanisms_department.edit_repair_request%}
  <div class="flex-col w-95">
    {% for req in Requests %}
      <div class="req-for-aggrement rtl w-100">
        {% csrf_token %}
        <input type="text" name="RepReq_ID" value="{{req.Request_ID}}" hidden>
        <label class="form-lbl w-10">رقم الطلب : {{req.Request_No}}</label>
        <label class="form-lbl w-15">رقم السيارة : {{req.Mechanism_No}}</label>
        <label class="form-lbl w-20">الكلفة التقديرية : {{req.Expected_Cost}}</label>
        <div class="">
          <label for="Approval">قيمة الموافقة</label>
          <input class="npt" type="number" name="Approval" placeholder="رقم صحيح(مثال : 100000)" required>
        </div>
        <input class="give-aggrement-btn give-agg-id-{{req.Request_ID}}" type="button" name="Give_Aggrement" value="موافق">
      </div>
    {% endfor %}
  </div>
{% else %}
  <h1>عذرا,ليس لديك صلاحيات لعرض هذه الصفحة.</h1>
{% endif %}
{% endblock MainContainer %}

templates/Fin_Dep/section_tasks.html
<div id="accordion" class="section-content rtl">
  <h3 class="section-title">طلبات الاصلاح</h3>
  <ul class='section-list'>
    <li> <a href="{% url 'Req_Aggrement' %}">طلبات بانتظار الموافقة</a> </li>
  </ul>
  <h3 class="section-title">أوامر الصرف</h3>
  <ul class='section-list'>
    <li> <a href="#">أمر صرف - اصلاح الآليات</a> </li>
  </ul>
  <h3 class="section-title">الموازنة</h3>
  <ul class='section-list'>
    <li> <a href="{% url 'Set_Main_Balance' %}">اعداد الموازنة الاساسية</a> </li>
    <li> <a href="{% url 'Set_SubBalance' %}">اعداد الموازنة فرعية</a> </li>
    <li> <a href="{% url 'Set_SubBalance_Item' %}">اعداد بنود المازنة فرعية</a> </li>
    <li> <a href="#">اضافة اعتماد الموازنة</a> </li>
    <li> <a href="{% url 'View_Balances' %}">استعراض الموازنة</a> </li>
  </ul>
</div>

templates/Fin_Dep/set_main_balance.html
{% extends 'base.html' %}

{% block SideBar %}
  {% include 'Fin_Dep/section_tasks.html' %}
{% endblock SideBar %}

{% block MainContainer %}
{% if perms.financial_department.add_main_balance %}
  <form class="main-balance-form w-90 flex-column rtl" action="{% url 'Setting_Main_Balance' %}" method="post">
    {% csrf_token %}
    <div class="main-balance-labels w-100 flex-row space-around my-10">
      <label class="form-lbl w-30 text-center">سنة الموازنة</label>
      <label class="form-lbl w-30 text-center">حجم الموازنة</label>
      <label class="form-lbl w-30 text-center">المدة الزمنية</label>
    </div>
    <div class="horizontal-line w-100 my-10"> </div>
    <div class="main-balance-inputs w-100 flex-row space-around my-10 rtl">
      <input class="form-npt w-30" type="text" name="Bal_Year" required>
      <input class="form-npt w-30" type="number" name="Bal_Volume" required>
      <select class="form-npt w-30 h-lh-40" name="Bal_Duration" required>
        <option value="سنوية">سنوية</option>
        <option value="نصف سنوية">نصف سنوية</option>
        <option value="ربع سنوية">ربع سنوية</option>
        <option value="شهرية">شهرية</option>
      </select>
    </div>
    <input type="submit" class="save-btn pointer" value="حفظ">
  </form>
{% else %}

{% endif %}
{% endblock MainContainer %}

templates/Fin_Dep/set_sub_balance_items.html
{% extends 'base.html' %}

{% block SideBar %}
  {% include 'Fin_Dep/section_tasks.html' %}
{% endblock SideBar %}

{% block MainContainer %}
{% if perms.financial_department.add_balance_items %}
  <form class="sub-balance-item-form flex-column w-90" action="{% url 'Setting_SubBalance_Item' %}" method="post">
    {% csrf_token %}
    <div class="sub-balance-item-labels w-100 flex-row space-around rtl my-10">
      <label class="form-lbl w-10 text-center">سنة الموازنة</label>
      <label class="form-lbl w-25 text-center">اسم الحساب</label>
      <label class="form-lbl w-25 text-center">البند</label>
      <label class="form-lbl w-15 text-center">حجم الرصيد</label>
      <label class="form-lbl w-10 text-center">المدة الزمنية</label>
    </div>
    <div class="horizontal-line w-100 my-10"> </div>
    <div class="sub-balance-item-inputs flex-column w-100">
      <div class="sub-balance-item-field w-100 flex-row space-around rtl my-10">
        <input class="form-npt w-10" type="text" name="SubBalItm_Year" value="{{Year}}" required>
        <input class="form-npt w-25" name="SubBalItm_Account" list="SubBalanceAccounts-List" required>
        <input class="form-npt w-25" type="text" name="SubBalItm_Item" required>
        <input class="form-npt w-15" type="number" name="SubBalItm_Volume" required>
        <select class="form-npt h-lh-40 w-10" name="SubBalItm_Duration" required>
          <option value="سنوية">سنوية</option>
          <option value="نصف سنوية">نصف سنوية</option>
          <option value="ربع سنوية">ربع سنوية</option>
          <option value="شهرية">شهرية</option>
        </select>
      </div>
    </div>
    <div class="horizontal-line w-100 my-10"> </div>
    <div class="pointer add-subbalance-item-field add-button my-10"> <span class="fa-solid fa-plus-circle"></span> </div>
    <input type="submit" class="save-btn pointer w-10 my-10" value="حفظ">
  </form>
  <datalist id="SubBalanceAccounts-List">
    {% for Account in Accounts %}
    <option value="{{Account}}">{{Account}}</option>
    {% endfor %}
  </datalist>
{% else %}
  <h1>عذرا,ليس لديك صلاحيات لعرض هذه الصفحة.</h1>
{% endif %}
{% endblock MainContainer %}

templates/Fin_Dep/set_sub_balances.html
{% extends 'base.html' %}

{% block SideBar %}
  {% include 'Fin_Dep/section_tasks.html' %}
{% endblock SideBar %}

{% block MainContainer %}
{% if perms.financial_department.add_sub_balances %}
  <form class="sub-balance-form w-90 flex-column justify-center" action="{% url 'Setting_SubBalance' %}" method="post">
    {% csrf_token %}
    <div class="sub-balance-labels w-100 flex-row space-around rtl my-10">
      <label class="form-lbl w-20 text-center">اسم الحساب</label>
      <label class="form-lbl w-20 text-center">سنة الموازنة</label>
      <label class="form-lbl w-20 text-center">حجم الرصيد</label>
      <label class="form-lbl w-20 text-center">المدة الزمنية</label>
    </div>
    <div class="horizontal-line w-100 my-10"> </div>
    <div class="sub-balance-inputs w-100 flex-column">
      <div class="sub-balance-field w-100 flex-row space-around rtl my-10">
        <input class="form-npt w-20" type="text" name="SubBal_Account" required>
        <input class="form-npt w-20" type="text" name="SubBal_Year" value="{{Year}}" required>
        <input class="form-npt w-20" type="number" name="SubBal_Volume" required>
        <select class="form-npt w-20 h-lh-40" name="SubBal_Duration" required>
          <option value="سنوية">سنوية</option>
          <option value="نصف سنوية">نصف سنوية</option>
          <option value="ربع سنوية">ربع سنوية</option>
          <option value="شهرية">شهرية</option>
        </select>
      </div>
    </div>
    <div class="horizontal-line w-100 my-10"> </div>
    <div class="pointer add-sub-balance-field add-button my-10"> <span class="fa-solid fa-plus-circle"></span> </div>
    <input type="submit" class="save-btn pointer w-10 my-10" value="حفظ">
  </form>
{% else %}
  <h1>عذرا,ليس لديك صلاحيات لعرض هذه الصفحة.</h1>
{% endif %}
{% endblock MainContainer %}

templates/Fin_Dep/setup_sup_balances.html
{% extends 'base.html' %}

{% block SideBar %}
  {% include 'Fin_Dep/section_tasks.html' %}
{% endblock SideBar %}

{% block MainContainer %}
{% if perms.financial_department.add_sub_balances and perms.financial_department.add_balance_items %}
  
{% else %}
  <h1>عذرا,ليس لديك صلاحيات لعرض هذه الصفحة.</h1>
{% endif %}
{% endblock MainContainer %}

templates/Fin_Dep/view_balances.html
{% extends 'base.html' %}

{% block SideBar %}
  {% include 'Fin_Dep/section_tasks.html' %}
{% endblock SideBar %}

{% block MainContainer %}
<div class="view-data-container">
  {% if perms.financial_department.view_main_balance and perms.financial_department.view_subbalances and perms.financial_department.view_subbalance_items and perms.mechanisms_department.view_repair_request and perms.mechanisms_department.view_statements %}
    <a class="view-data-link" href="{% url 'View_Repair_Balance' %}">اصلاح الآليات</a>
</div>
{% endif %}
{% endblock MainContainer %}

templates/Fin_Dep/view_repair_balance.html
{% extends 'base.html' %}

{% block SideBar %}
  {% include 'Fin_Dep/section_tasks.html' %}
{% endblock SideBar %}

{% block MainContainer %}
{% if perms.financial_department.view_main_balance and perms.financial_department.view_subbalances and perms.financial_department.view_subbalance_items %}
  <div id="accordion-2" class="balances-sections">
    <h2 class="balance-title">موازنة القيادة المركزية</h2>
    <div class="balance-content">
      {{Data_1|safe}}
    </div>
    <h2 class="balance-title">موازنة الجبهة الوطنية التقدمية</h2>
    <div class="balance-content">
      {{Data_2|safe}}
    </div>
    <h2 class="balance-title">موازنة الاتصال القومي</h2>
    <div class="balance-content">
      {{Data_3|safe}}
    </div>
    <h2 class="balance-title">موازنة كتائب البعث</h2>
    <div class="balance-content">
      {{Data_4|safe}}
    </div>
    <h2 class="balance-title">موازنة لجنة الرقابة و التفتيش الحزبية</h2>
    <div class="balance-content">
      {{Data_5|safe}}
    </div>
  </div>
{% else %}

{% endif %}
{% endblock MainContainer %}