CC_Adminstration/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home_Page, name='Home_Page'),
    path('accounts/', include('Accounts.urls')),
    path('general/', include('General.urls')),
    path('mech_dep/', include('Mechanisms_Department.urls')),
    path('fin_dep/', include('Financial_Department.urls')),
    path('sections/', include('Sections.urls')),
    #path('authen/', include('django.contrib.auth.urls')),
]

General/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('permissions/', views.Permissions_Page, name='Permissions_Page'),
    path('save_permissions/', views.Save_Permissions, name='Save_Permissions'),
]

Mechanisms_Department/models.py
from django.db import models

# Create your models here.
class Mechanism_Data(models.Model):
    MechanismID     = models.CharField(primary_key=True, max_length=6, unique=True)
    Ownership       = models.CharField(max_length=48, blank=True, default='D')
    Disposal        = models.CharField(max_length=120, blank=True, default='D')
    Brand           = models.CharField(max_length=320, blank=True, default='D')
    Model           = models.CharField(max_length=320, blank=True, default='D')
    Type            = models.CharField(max_length=320, blank=True, default='D')
    Fuel_Limit      = models.IntegerField(blank=True, default=0)
    Repair_Limit    = models.IntegerField(blank=True, default=0)

    def __str__(self):
        return str(self.MechanismID)


class Statements(models.Model):
    Statement_ID    = models.CharField(primary_key=True, unique=True, max_length=128)
    Requests_No     = models.CharField(max_length=320, blank=True, default='D')
    Statement_No    = models.CharField(max_length=3, blank=True, default='D')
    SubBalance      = models.CharField(max_length=32, blank=True, default='D')
    Statement_Value = models.IntegerField(blank=True, default=0)
    Statement_Type  = models.CharField(max_length=6, blank=True, default='D')
    Year            = models.CharField(max_length=4, blank=True, default='D')

    def __str__(self):
        return str(self.Statement_ID)


class Repair_Requests(models.Model):
    Request_ID     = models.CharField(primary_key=True, unique=True, max_length=16)
    Request_No     = models.CharField(max_length=10, blank=True, default='D')
    Request_Date   = models.DateField(auto_now=False, auto_now_add=False)
    Year           = models.CharField(max_length=16, blank=True, default='D')
    Month          = models.CharField(max_length=16, blank=True, default='D')
    Day            = models.CharField(max_length=16, blank=True, default='D')
    Mechanism_No   = models.ForeignKey(Mechanism_Data, on_delete=models.CASCADE, blank=True, default='D')
    KiloMeters     = models.IntegerField(blank=True, default=0)
    Ownership      = models.CharField(max_length=48, blank=True, default='D')
    Disposal       = models.CharField(max_length=120, blank=True, default='D')
    Model          = models.CharField(max_length=320, blank=True, default='D')
    Expected_Cost  = models.IntegerField(blank=True, default=0)
    Approval       = models.IntegerField(blank=True, default=0)
    Exchange_Date  = models.DateField(auto_now=False, auto_now_add=False, blank=True, null=True)
    Driver         = models.CharField(max_length=64, blank=True, default='D')
    Real_Cost      = models.IntegerField(blank=True, default=0)
    Repair_Type    = models.CharField(max_length=16, default='صيانة طارئة')
    Status         = models.CharField(max_length=32, blank=True, default='D')
    Statement      = models.CharField(max_length=64, blank=True, default='D')

    def __str__(self):
        return str(self.Request_ID)


class Mechanisms_Repairs(models.Model):
    Request_ID   = models.ForeignKey(Repair_Requests, on_delete=models.CASCADE, default='D')
    Mechanism_No = models.CharField(max_length=6, blank=True, default='D')
    Request_Date = models.DateField(auto_now=False, auto_now_add=False, blank=True, null=True)
    Year         = models.CharField(max_length=4, blank=True, default='D')
    Month        = models.CharField(max_length=2, blank=True, default='D')
    Day          = models.CharField(max_length=2, blank=True, default='D')
    KiloMeters   = models.CharField(max_length=6, blank=True, default='D')
    Part_Repair  = models.CharField(max_length=120, blank=True, default='D')
    Part_Count   = models.IntegerField(blank=True, default=0)
    Part_Type    = models.CharField(max_length=32, blank=True, default='D')
    Cost         = models.IntegerField(blank=True, default=0)
    Receipt_No   = models.CharField(max_length=6, blank=True, default='D')
    Store        = models.CharField(max_length=64, blank=True, default='D')


    def __str__(self):
        return self.Part_Repair


class Parts_and_Repaires(models.Model):
    Name = models.CharField(max_length=320, blank=True, default='D')
    Type = models.CharField(max_length=320, blank=True, default='D')

    def __str__(self):
        return self.Name


class Drivers(models.Model):
    Driver_Name  = models.CharField(max_length=64, blank=True, default='D')
    Office       = models.CharField(max_length=64, blank=True, default='D')
    Mechanism_No = models.ForeignKey(Mechanism_Data, on_delete=models.CASCADE, blank=True, default='D')
    Disposal     = models.CharField(max_length=64, blank=True, default='D')

    def __str__(self):
        return self.Driver_Name


class Stores(models.Model):
    Store_Name = models.CharField(max_length=64, blank=True, default='D')
    Address    = models.CharField(max_length=128, blank=True, default='D')
    Email      = models.CharField(max_length=64, blank=True, default='D')
    PhoneNo    = models.CharField(max_length=16, blank=True, default='D')
    Mobile     = models.CharField(max_length=16, blank=True, default='D')

    def __str__(self):
        return self.Store_Name


class Receipts(models.Model):
    Receipt_ID    = models.CharField(primary_key=True, unique=True, max_length=64)
    Receipt_No    = models.CharField(max_length=16, blank=True, default='D')
    Request_ID    = models.ForeignKey(Repair_Requests, on_delete=models.CASCADE, blank=True, default='D')
    Receipt_Value = models.IntegerField(blank=True, default=0)
    Store_Name    = models.CharField(max_length=32, blank=True, default='D')
    Receipt_Date  = models.DateField(auto_now=False, auto_now_add=False)

    def __str__(self):
        return f"{self.Receipt_ID}__{self.Store_Name}"

templates/Mech_Dep/add_receipt.html
{% extends 'base.html' %}

{% block SideBar %}
  {% include 'Mech_Dep/section_tasks.html' %}
{% endblock SideBar %}

{% block MainContainer %}
{% if perms.mechanisms_department.add_receipts %}
  <form class="add-receipt-form rtl flex-column justify-center" method="post" action="{% url 'Adding_Receipt' %}">
    {% csrf_token %}
    <div class="receipt-g1 flex-row-wrap w-60 space-around my-10">
      <input class="form-npt w-40 h-lh-30 my-5" type="text" name="RepReq_No" placeholder="رقم الطلب*" required>
      <input class="form-npt w-40 h-lh-30 my-5" type="text" name="Year" placeholder="السنة*" required>
      <label class="get-receipt-details form-lbl w-60 my-10 text-center pointer bg-lime h-lh-30 my-5">موافق</label>
    </div>
    <div class="horizontal-line w-100"></div>
    <div class="receipt-g2-container my-10 w-90 hidden">
      <div class="receipt-g2-titles flex-row space-around rtl my-10">
        <label class="w-20 text-center">رقم الفاتورة</label>
        <label class="w-20 text-center">تاريخ الفاتورة</label>
        <label class="w-20 text-center">قيمة الفاتورة</label>
        <label class="w-20 text-center">التاجر</label>
      </div>
      <div class="receipt-g2 my-5">
        <input class="form-npt w-20 rtl" type="text" name="A_Receipt_No" required>
        <input class="form-npt w-20 rtl" type="date" name="A_Receipt_Date" required>
        <input class="form-npt w-20 rtl" type="text" name="A_Receipt_Value" required>
        <input class="form-npt w-20 rtl" type="text" name="A_Store_Name" required>
      </div>
    </div>
    <div class="pointer add-receipt-button hidden"> <span class="fa-solid fa-plus-circle"></span> </div>
    <div class="horizontal-line w-100"></div>
    <div class="receipt-g3-container flex-col my-10 hidden">
      <div class="receipt-g3-titles w-100 flex-row space-around text-center">
        <label class="w-30">بيان الاصلاحات</label>
        <label class="w-30p">العدد</label>
        <label class="w-10">النوع</label>
        <label class="w-10">التكلفة</label>
        <label class="w-60p">رقم الفاتورة</label>
        <label class="w-20">التاجر</label>
      </div>
      <div class="receipt-g3">
        <input type="text" name="Repair_ID" hidden>
        <input class="w-30 form-npt" type="text" name="Repairs" placeholder="بيان الاصلاحات*" list="Repairs_List" readonly>
        <input class="w-30p form-npt" type="number" name="Quantity" placeholder="العدد" valu="1" required>
        <input class="w-10 form-npt" type="text" name="Type" placeholder="النوع">
        <input class="w-10 form-npt" type="number" name="Cost" placeholder="التكلفة (= 0)" value="0" required>
        <input class="w-60p form-npt" type="text" name="Receipt_No" placeholder="رقم الفاتورة">
        <input class="w-20 form-npt" type="text" name="Store_Name" placeholder="التاجر" list="Stores-List">
      </div>
    </div>
    <input type="submit" class="pointer save-receipt-btn hidden" value="حفظ">
  </form>
  <datalist id="Stores-List">
    {% for Store in Stores  %}
    <option value="{{ Store }}"></option>
    {% endfor %}
  </datalist>
{% else %}
  <h1>عذرا,ليس لديك صلاحيات لعرض هذه الصفحة.</h1>
{% endif %}
{% endblock MainContainer %}

templates/Mech_Dep/add_repreq.html
{% extends 'base.html' %}

{% block SideBar %}
  {% include 'Mech_Dep/section_tasks.html' %}
{% endblock SideBar %}

{% block MainContainer %}
{% if perms.mechanisms_department.add_repair_request %}
  <form class="add-repreq-form rtl flex-column" method="post" action="{% url 'Adding_Rep_Req' %}">
    {% csrf_token %}
    <div class="flex-row repreq-g1">
      <input id="Mech-ID" class="w-10 form-npt mech-id" list="MechsID-List" type="text" name="Mech_ID" placeholder="رقم السيارة*" required>
      <label id="Mech-Model" class="w-20 form-lbl text-center"></label>
      <label id="Mech-Ownership" class="w-30 form-lbl text-center"></label>
      <label id="Mech-Disposal" class="w-30 form-lbl text-center"></label>
    </div>
    <div class="horizontal-line"></div>
    <div class="repreq-g2">
      <input class="w-30 form-npt" type="number" name="Req_No" placeholder="رقم الطلب*" required>
      <input class="w-30 form-npt" type="text" name="Req_Date" placeholder="تاريخ الطلب  05/12/2022" onfocus="(this.type='date')" onblur="(this.type='text')" required>
      <input class="w-30 form-npt" type="number" name="Kilometers" placeholder="رقم العداد">
      <input class="w-30 form-npt" type="text" name="Driver_Name" placeholder="اسم السائق*" list="Drivers-List" required>
      <input class="w-30 form-npt" type="number" name="Approval" placeholder="الموافقة (الافتراضية = 0)" value="0" required>
      <input class="w-30 form-npt" type="number" name="Expected_Cost" placeholder="التكلفة التقديرية (الافتراضية = 0)" value="0" required>
      <select class="w-30 form-npt h-lh-40" name="Rep_Type">
        <option value="صيانة دورية" checked>صيانة دورية</option>
        <option value="صيانة طارئة">صيانة طارئة</option>
      </select>
    </div>
    <div class="repreq-status">
      <label class="repreq-status-title">حالة الطلب</label>
      <div class="repreq-status-options">
        <div>
          <input id="status-1" type="radio" name="RepReq_Status" value="بانتظار الموافقة" checked>
          <label for="status-1">بانتظار الموافقة</label>
        </div>
        <div>
          <input id="status-2" type="radio" name="RepReq_Status" value="قيد التنفيذ">
          <label for="status-2">قيد التنفيذ</label>
        </div>
        <div>
          <input id="status-3" type="radio" name="RepReq_Status" value="تم التنفيذ">
          <label for="status-3">تم التنفيذ</label>
        </div>
        <div>
          <input id="status-4" type="radio" name="RepReq_Status" value="مصروف">
          <label for="status-4">مصروف</label>
        </div>
      </div>
    </div>
    <div class="horizontal-line"></div>
    <div class="repreq-g3-container flex-col">
      <div class="repreq-g3">
        <input class="w-30 form-npt" type="text" name="Repairs" placeholder="بيان الاصلاحات*" list="Repairs_List" required>
        <input class="w-30p form-npt" type="number" name="Quantity" placeholder="العدد">
        <input class="w-10 form-npt" type="text" name="Type" placeholder="النوع">
        <input class="w-10 form-npt" type="number" name="Cost" placeholder="التكلفة (= 0)" value="0" required>
        <input class="w-60p form-npt" type="text" name="Receipt_No" placeholder="رقم الفاتورة">
        <input class="w-20 form-npt" type="text" name="Store_Name" placeholder="التاجر" list="Stores-List">
      </div>
    </div>
    <div class="pointer add-g3-button"> <span class="fa-solid fa-plus-circle"></span> </div>
    <input type="submit" class="pointer w-100p save-repreq-btn" name="" value="حفظ">
  </form>
  <datalist id="MechsID-List">
    {% for Mech in MechsID %}
      <option value="{{ Mech }}"></option>
    {% endfor %}
  </datalist>
  <datalist id="Stores-List">
    {% for Store in Stores  %}
      <option value="{{ Store }}"></option>
    {% endfor %}
  </datalist>
  <datalist id="Drivers-List">
    {% for Driver in Drivers %}
      <option value="{{ Driver }}"></option>
    {% endfor %}
  </datalist>
  <datalist id="Repairs-List">
    {% for Repair in Repairs %}
      <option value="{{ Repair }}"></option>
    {% endfor %}
  </datalist>
  <datalist id="RepType-List">
    
  </datalist>
{% else %}
  <h1>عذرا,ليس لديك صلاحيات لعرض هذه الصفحة.</h1>
{% endif %}
{% endblock MainContainer %}

templates/Mech_Dep/add_statement.html
{% extends 'base.html' %}

{% block SideBar %}
  {% include 'Mech_Dep/section_tasks.html' %}
{% endblock SideBar %}

{% block MainContainer %}
{% if perms.mechanisms_department.add_statement %}
  <form class="add-receipt-form rtl flex-column justify-center" method="post" action="{% url 'Adding_Statement' %}">
    {% csrf_token %}
    <div class="statement-g2-container my-10 w-90">
      <div class="statement-g2-titles w-100 flex-row space-around rtl my-10">
        <label class="w-10 text-center">الرقم</label>
        <label class="w-10 text-center">السنة</label>
        <label class="w-20 text-center">القيمة</label>
        <label class="w-30 text-center">الميزانية</label>
        <label class="w-20 text-center">النوع</label>
      </div>
      <div class="statement-g2">
        <input class="form-npt w-10 rtl" type="text" name="Statement_No" required>
        <input class="form-npt w-10 rtl" type="text" name="Statement_Year" required>
        <input class="form-npt w-20 rtl" type="text" name="Statement_Value" required>
        <input class="form-npt w-30 rtl" type="text" name="SubBalance" required>
        <input class="form-npt w-20 rtl" type="text" name="Statement_Type" required>
      </div>
    </div>
    <div class="horizontal-line w-100 my-10"></div>
    <div class="statement-g3-container w-100 flex-column">
      <div class="w-40 flex-row justify-start">
        <input class="form-npt w-20 mx-10" type="number" name="RepReqs_Count" placeholder="عدد الطلبات*">
        <div class="pointer add-statement-field-button mx-10"> <span class="fa-solid fa-plus-circle"></span> </div>
      </div>
      <div class="horizontal-line w-100 my-10"></div>
      <label class="form-lbl w-98 text-right my-10">ارقام الطلبات</label>
      <div class="statement-g3 w-70 flex-row-wrap justify-start">
        <input class="repreq-statement form-npt w-40p m-10" type="text" name="RepReq_No" value="" required>
      </div>
    </div>
    <div class="horizontal-line w-100"></div>
    <input type="submit" class="pointer w-100p save-statement-btn" value="حفظ">
  </form>
{% else %}
  <h1>عذرا,ليس لديك صلاحيات لعرض هذه الصفحة.</h1>
{% endif %}
{% endblock MainContainer %}

templates/Mech_Dep/change_repreq_status.html
{% extends 'base.html' %}

{% block SideBar %}
  {% include 'Mech_Dep/section_tasks.html' %}
{% endblock SideBar %}

{% block MainContainer %}
{% if perms.mechanisms_department.edit_repair_request %}
  <form class="change-repreq-status-form rtl flex-column w-50 space-around" method="post" action="{% url 'Changing_RepReq_Status' %}">
    {% csrf_token %}
    <input class="w-60 form-npt my-10" type="text" name="RepReq_No" placeholder="رقم الطلب*" required>
    <!-- <input class="w-60 form-npt my-10" type="text" name="RepReq_Year" placeholder="السنة*" required> -->
    <select class="w-60 form-npt my-10 h-lh-35" name="RepReq_Status">
      <option value="بانتظار الموافقة"> بانتظار الموافقة </option>
      <option value="قيد التنفيذ"> قيد التنفيذ </option>
      <option value="تم التنفيذ"> تم التنفيذ </option>
      <option value="مصروف"> مصروف </option>
      <option value="ملغى"> ملغى </option>
    </select>
    <input type="submit" class="pointer w-60 save-repreq-status-btn my-10" name="" value="حفظ">
  </form>
{% else %}
  <h1>عذرا,ليس لديك صلاحيات لعرض هذه الصفحة.</h1>
{% endif %}
{% endblock MainContainer %}

templates/Mech_Dep/edit_repreq.html
{% extends 'base.html' %}

{% block SideBar %}
  {% include 'Mech_Dep/section_tasks.html' %}
{% endblock SideBar %}

{% block MainContainer %}
{% if perms.mechanisms_department.edit_repair_request %}
  <form class="edit-repreq-form rtl w-90 my-0 flex-column justify-center" action="{% url 'Editing_RepReq' %}" method="post">
    {% csrf_token %}
    <div class="editdetails-form w-60 flex-column justify-center my-0 rtl">
      <div class="flex-row space-around w-100 my-10">
        <input class="form-npt w-40" type="text" name="RepReq_No" placeholder="رقم الطلب*" required>
        <input class="form-npt w-40" type="text" name="RepReq_Year" placeholder="السنة*" required>
      </div>
      <select class="edit-type form-npt w-90 hl-30p my-10 h-lh-40" name="Editing_Type" >
        <option value="getRepairRequestData" checked>تعديل بيانات الطلب</option>
        <option value="getRepairsDetails">تعديل تفاصيل الاصلاح</option>
        <option value="getRepairsDetailsD">حذف اصلاحات</option>
      </select>
      <label class="get-editform form-lbl w-60 my-10 text-center pointer bg-lime h-lh-40">موافق</label>
    </div>
    <!-- Repair Request Data -->
    <div class="edit-repreqdata-form repreq-g2-edit-container repreq-g2-edit" style="display:none;">
      <input class="w-30 form-npt" type="text" name="Mech_ID" placeholder="رقم الآلية*">
      <input class="w-30 form-npt" type="text" name="Req_Date" placeholder="تاريخ الطلب  /يوم/شهر/سنة">
      <input class="w-30 form-npt" type="text" name="Kilometers" placeholder="رقم العداد">
      <input class="w-30 form-npt" type="text" name="Driver_Name" placeholder="اسم السائق*" list="Drivers-List">
      <input class="w-30 form-npt" type="number" name="Approval" placeholder="الموافقة*">
      <input class="w-30 form-npt" type="number" name="Expected_Cost" placeholder="الكلفة الاجمالية التقديرية">
      <select class="w-30 form-npt h-lh-40" name="Rep_Type">
        <option value="صيانة دورية" checked>صيانة دورية</option>
        <option value="صيانة طارئة">صيانة طارئة</option>
      </select>
    </div>
    <!-- Repairs Details -->
    <div class="edit-repairsdetails-form hidden">
      <div class="repreq-g3-edit-container flex-column justify-center">
        <div class="repreq-g3-edit">
          <input type="text" name="Repair_ID" value="New_ID" hidden>
          <input class="w-40 form-npt" type="text" name="Repairs" placeholder="بيان الاصلاحات*" list="Repairs_List">
          <input class="w-30p form-npt" type="number" name="Quantity" placeholder="العدد" value="1">
          <input class="w-10 form-npt" type="text" name="Type" placeholder="النوع">
          <input class="w-10 form-npt" type="number" name="Cost" placeholder="الكلفة" value="0" readonly>
          <input class="w-10 form-npt" type="text" name="Receipt_No" placeholder="رقم الفاتورة" readonly>
          <input class="w-10 form-npt" type="text" name="Store_Name" placeholder="التاجر*" list="Stores-List" readonly>
        </div>
      </div>
      <div class="pointer add-g3edit-button"> <span class="fa-solid fa-plus-circle"></span> </div>
    </div>
    <!-- Delete Repairs Details  -->
    <div class="delete-repairsdetails-form repreq-g3-container-d flex-column justify-center" style="display:none;">
      <div class="repreq-g3-d">
        <input type="text" name="D_Repair_ID" value="New_ID" hidden>
        <input class="w-40 form-npt" type="text" name="D_Repairs" placeholder="بيان الاصلاحات*" list="Repairs_List" readonly>
        <input class="w-30p form-npt" type="number" name="D_Quantity" placeholder="العدد" value="1" readonly>
        <input class="w-10 form-npt" type="text" name="D_Type" placeholder="النوع" readonly>
        <input class="w-10 form-npt" type="number" name="D_Cost" placeholder="الكلفة" value="0" readonly>
        <input class="delete-repair-button" type="button" value="حذف" onclick="deleteRepair(this);">
      </div>
    </div>
    <input type="submit" class="pointer edit-repreq-btn hidden" value="حفظ التغييرات">
  </form>
  <!-- Data Lsts fpr Inputs -->
  <datalist id="Stores-List">
    {% for Store in Stores  %}
      <option value="{{ Store }}"></option>
    {% endfor %}
  </datalist>
  <datalist id="Drivers-List">
    {% for Driver in Drivers %}
      <option value="{{ Driver }}"></option>
    {% endfor %}
  </datalist>
  <datalist id="Repairs-List">
    {% for Repair in Repairs %}
      <option value="{{ Repair }}"></option>
    {% endfor %}
  </datalist>
{% else %}
  <h1>عذرا,ليس لديك صلاحيات لعرض هذه الصفحة.</h1>
{% endif %}
{% endblock MainContainer %}

templates/Mech_Dep/enter_data.html
{% extends 'base.html' %}

{% block SideBar %}
  {% include 'Mech_Dep/section_tasks.html' %}
{% endblock SideBar %}

{% block MainContainer %}
  <form class="enter-data-form w-100 flex-column justify-center rtl" action="index.html" method="post">
    {% csrf_token %}
    <select class="w-30 my-10" name="Table_Name">
      <option value="entering_drivers">جدول السائقين</option>
      <option value="entering_stores">جدول التجار</option>
      <option value="entering_parts_repairs">جدول القطع و الاصلاحات</option>
    </select>
    <label class="add-form-table form-lbl w-30 my-10 text-center pointer bg-lime h-lh-40">موافق</label>
    <div class="horizontal-line my-10 w-100"></div>
    <div class="table-form flex-column justify-center w-100" style="display:none;">
      <div class="drivers-table-field flex-row space-around my-10 rtl w-90 ">
        <input class="w-20 form-npt rtl" type="text" name="" placeholder="اسم السائق*" required>
        <input class="w-30 form-npt rtl" type="text" name="" placeholder="المكتب">
        <input class="w-10 form-npt rtl" type="text" name="" placeholder="رقم السيارة">
        <input class="w-30 form-npt rtl" type="text" name="" placeholder="تحت تصرف">
      </div>
      <div class="stores-table-field flex-row space-around my-10 rtl w-90">
        <input class="w-20 form-npt rtl" type="text" name="" placeholder="التاجر*" required>
        <input class="w-20 form-npt rtl" type="text" name="" placeholder="العنوان">
        <input class="w-20 form-npt rtl" type="text" name="" placeholder="البريد الالكتروني">
        <input class="w-15 form-npt rtl" type="text" name="" placeholder="رقم الهاتف / الفاكس">
        <input class="w-15 form-npt rtl" type="text" name="" placeholder="رقم الموبايل">
      </div>
      <div class="parts-table-field flex-row space-around my-10 rtl w-90">
        <input class="w-40 form-npt rtl" type="text" name="" value="" placeholder="اسم القطع / الاصلاحات" required>
        <select class="w-20 h-lh-35 form-npt" name="">
          <option value="صيانة دورية">صيانة دورية</option>
          <option value="صيانة طارئة">صيانة طارئة</option>
        </select>
      </div>
    </div>
    <div class="pointer add-table-field-button hidden"> <span class="fa-solid fa-plus-circle"></span> </div>
    <input class="pointer save-btn w-100p hidden" type="submit" value="حفظ">
  </form>
{% endblock MainContainer %}

templates/Mech_Dep/section_tasks.html
<div id="accordion" class="section-content rtl">
  <h3 class="section-title">طلبات الاصلاح</h3>
  <ul class='section-list'>
    <li> <a href="{% url 'Add_Rep_Req' %}">اضافة طلب</a> </li>
    <li> <a href="{% url 'Edit_Rep_Req' %}">تعديل طلب</a> </li>
    <li> <a href="{% url 'Add_Receipts' %}">اضافة فاتورة</a> </li>
    <li> <a href="#">تعديل فاتورة</a> </li>
    <li> <a href="{% url 'Add_Statement' %}">اضافة كشف</a> </li>
    <li> <a href="#">تعديل كشف</a> </li>
    <li> <a href="{% url 'Change_RepReq_Status' %}">تغيير حالة الطلب</a> </li>
  </ul>
  <h3 class="section-title">البيانات</h3>
  <ul class='section-list'>
    <li> <a href="{% url 'Enter_Data' %}">ادخال البيانات</a> </li>
    <li> <a href="{% url 'View_Data' %}">استعراض جداول البيانات</a> </li>
    <li> <a href="{% url 'View_Data_Filtering_Page' %}">استعراض مخصص للبيانات</a> </li>
    <li> <a href="#">بيانات الآليات</a> </li>
  </ul>
</div>

templates/Mech_Dep/show_requests.html
{% extends 'base.html' %}

{% block SideBar %}
  {% include 'Mech_Dep/section_tasks.html' %}
{% endblock SideBar %}

{% block MainContainer %}

{% endblock MainContainer %}

templates/Mech_Dep/view_data.html
{% extends 'base.html' %}

{% block SideBar %}
  {% include 'Mech_Dep/section_tasks.html' %}
{% endblock SideBar %}

{% block MainContainer %}
<div class="view-data-container rtl">
  <a class="view-data-link" href="{% url 'View_RepReqs' %}" target="_blank">عرض جدول طلبات الاصلاح</a>
  <a class="view-data-link" href="{% url 'View_MechsReps' %}" target="_blank">عرض جدول الاصلاحات</a>
  <a class="view-data-link" href="{% url 'View_Data_Table' 'Receipts' %}" target="_blank">عرض جدول الفواتير</a>
  <a class="view-data-link" href="{% url 'View_Data_Table' 'Statements' %}" target="_blank">عرض جدول الكشوف</a>
  <a class="view-data-link" href="" target="_blank"></a>
</div>
{% endblock MainContainer %}

templates/Mech_Dep/view_data_filtering.html
{% extends 'base.html' %}

{% block SideBar %}
  {% include 'Mech_Dep/section_tasks.html' %}
{% endblock SideBar %}

{% block MainContainer %}
<div class="flex-row space-around rtl my-10 w-90">
  <label class="w-25 text-center">اسم الجدول</label>
  <label class="w-20 text-center">تصفية حسب</label>
  <label class="w-20 text-center">عامل التصفية</label>
  <label class="w-20 text-center">السنة</label>
</div>
<div class="horizontal-line w-90"></div>
<div class="flex-row-wrap space-around rtl my-10 w-90">
  <select class="w-25 form-npt h-lh-40 rtl" name="Table">
    <option value="No Table Name" checked>اختر اسم جدول...</option>
    <option value="Repair_Requests">طلبات الاصلاح</option>
    <option value="Mechanisms_Repairs">الاصلاحات</option>
  </select>
  <select class="w-20 form-npt h-lh-40 rtl" name="Filter">

  </select>
  <select class="w-20 form-npt h-lh-40 rtl" name="Keyword">

  </select>
  <select class="w-20 form-npt h-lh-40 rtl" name="Year">

  </select>
</div>
<label class="view-data-filtering form-lbl w-20 text-center pointer bg-lime h-lh-40">عرض</label>
{% endblock MainContainer %}